# Generated by Django 4.2.13 on 2025-08-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('student_name', models.CharField(blank=True, max_length=120)),
                ('content', models.TextField()),
                ('score_overall', models.FloatField(default=0)),
                ('score_length', models.FloatField(default=0)),
                ('score_clarity', models.FloatField(default=0)),
                ('score_vocabulary', models.FloatField(default=0)),
                ('score_readability', models.FloatField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
