# Generated by Django 4.2.13 on 2025-08-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='analysis',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='essay',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
